### PR TITLE
Use go-scp

### PR DESCRIPTION
**Pull request by harakeishi**
# summary
With the change in https://github.com/takutakahashi/database-restore-action/pull/4 , scp is supported, but we found the following problems.

problems: scp at [github.com/viant/afs](https://github.com/viant/afs) uses too much memory to transfer large files.
The following example shows a file of approximately 28 GB being transferred.
スクリーンショット 2023-05-19 18 38 01

As you can see, as much as 5 GB of memory is being used during the process.
As the transfer progressed, the amount of memory used increased.

In light of the above, we will stop using `github.com/viant/afs` and change to using [github.com/bramvdbogaerde/go-scp](https://github.com/bramvdbogaerde/go-scp).

Using `github.com/bramvdbogaerde/go-scp`, we did not use a lot of memory during the transfer as shown below.
スクリーンショット 2023-05-19 17 22 19

### CODE REVIEW

**Comment by harakeishi** [comment]
@takutakahashi 
Sorry for the repetition, but please check back when you are free.

**Review by takutakahashi — APPROVED** [review]
LGTM!

**Comment by takutakahashi** [comment]
released!

**Comment by harakeishi** [comment]
Thank you for your review and release work 🙏

**Pull request merged**
